services:
  - type: web
    name: warehouse-pdf-processor
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    autoDeploy: true
